<?php

namespace app\modules\vehicle\models;

use app\modules\Fanavaran\models\core\Conf;
use app\modules\Fanavaran\models\HttpCarLookup;
use Yii;

/**
 * This is the model class for table "plaque_kind".
 *
 * @property int $id
 * @property int|null $vehicle_group_id
 * @property string|null $name_fa
 * @property string|null $name_en
 * @property int|null $active
 */
class PlaqueKind extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'plaque_kind';
    }

    public function fields()
    {
        $parent = parent::fields(); // TODO: Change the autogenerated stub
//        $parent = [];
        $parent['name'] = function () {
            return $this->name_fa;
        };
        $parent['value'] = function () {
            return $this->id;
        };

        return $parent;
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vehicle_group_id', 'active'], 'integer'],
            [['name_fa', 'name_en'], 'string', 'max' => 255],
        ];
    }


    public static function insertFan()
    {
        $http  = new HttpCarLookup();
        $data = $http->plaqueKinds();
        if ($data['status'])
        {
            $data = Conf::mapPascalCaseToSnakeCase($data['response']);
            $trans = Yii::$app->db->beginTransaction();
            try {
                foreach ($data as $kay ) {
                    $model = PlaqueKind::findOne(['id' => $kay['id']]);
                    if (empty($model))
                    {
                        $model = new PlaqueKind();
                    }
                    $model->name_fa = $kay['caption'];
                    $model->name_en = $kay['name'];
                    $model->vehicle_group_id = $kay['vehicle_group_id'];
                    $model->id = $kay['id'];
                    $model->active = $kay['is_active'];
                    if (!$model->save()) {
                        $trans->rollBack();
                        return $model->errors;
                    }
                }
                $trans->commit();
                return  true;
            }catch (\Exception $err)  {
                $trans->rollBack();
                return  $err;
            }

        }
        return  $data;
    }



    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vehicle_group_id' => 'Vehicle Group ID',
            'name_fa' => 'Name Fa',
            'name_en' => 'Name En',
            'active' => 'Active',
        ];
    }
}
