<?php

namespace app\modules\Fanavaran\controllers;

use app\modules\common\models\AccessoryKind;
use app\modules\common\models\AdditionalCov;
use app\modules\common\models\Areas;
use app\modules\common\models\BasicCov;
use app\modules\common\models\CalcKind;
use app\modules\common\models\Cites;
use app\modules\common\models\Countries;
use app\modules\common\models\DmgCaseType;
use app\modules\common\models\DriverType;
use app\modules\common\models\InsuranceCorp;
use app\modules\common\models\InsuranceFinalStatus;
use app\modules\common\models\InsuranceLine;
use app\modules\common\models\InsuranceLineCategory;
use app\modules\common\models\IsAns;
use app\modules\common\models\IsHas;
use app\modules\common\models\LossesHistory;
use app\modules\common\models\Provinces;
use app\modules\common\models\VehicleHullDiscounts;
use app\modules\vehicle\models\PlaqueDesign;
use app\modules\vehicle\models\PlaqueKind;
use app\modules\vehicle\models\PlaqueLetter;
use app\modules\vehicle\models\PlaqueSample;
use app\modules\vehicle\models\VehicleFuelType;
use app\modules\vehicle\models\VehicleGroup;
use app\modules\vehicle\models\VehicleKind;
use app\modules\vehicle\models\VehicleSystem;
use app\modules\vehicle\models\VehicleUseType;
use yii\web\Controller;
use yii\web\Response as webResponse;

class LookupUpdateController extends Controller
{

    public function behaviors(): array
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub


        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

        return $parent;
    }

    public function actionInsuranceCorp() {
        return InsuranceCorp::insertFan();
    }


    public function actionInsuranceLineCategory(){
        return InsuranceLineCategory::insertFan();
    }


    public function actionInsuranceLine() {
        return InsuranceLine::insertFan();
    }

    public function actionInsuranceFinalStatus() {
        return InsuranceFinalStatus::insertFan();
    }


    public function actionDmgCaseType() {
        return DmgCaseType::insertFan();
    }

    public function actionCountries() {
        return Countries::insertFan();
    }

    public function actionProvinces() {
        return Provinces::insertFan();
    }


    public function actionCites() {
        return Cites::insertFan();
    }

    public function actionAreas() {
        return Areas::insertFan();
    }


    public function actionCalcKinds() {
        return CalcKind::insertFan();
    }


    public function actionAns() {
        return IsAns::insertFan();
    }


    public function actionHas() {
        return IsHas::insertFan();
    }


    public function actionLossesHistory() {
        return LossesHistory::insertFan();
    }

    public function actionBasicCov() {
        return BasicCov::insertFan();
    }

    public function actionAdditionalCov() {
        return AdditionalCov::insertFan();
    }


    public function actionDriverType() {
        return DriverType::insertFan();
    }


    public function actionVehicleHullDiscount() {
        return VehicleHullDiscounts::insertFan();
    }


    public function actionVehicleGroup() {
        return VehicleGroup::insertFan();
    }


    public function actionVehicleType() {
        return VehicleUseType::insertFan();
    }

    public function actionVehicleSystem() {
        return VehicleSystem::insertFan();
    }

    public function actionVehicleKinds() {
        return VehicleKind::insertFan();
    }

    public function actionVehicleFuelType() {
        return VehicleFuelType::insertFan();
    }

    public function actionPlaqueKinds() {
        return PlaqueKind::insertFan();
    }

    public function actionPlaqueLetter() {
        return PlaqueLetter::insertFan();
    }

    public function actionPlaqueSample() {
        return PlaqueSample::insertFan();
    }

    public function actionPlaqueDesign() {
        return PlaqueDesign::insertFan();
    }


    public function actionAccessoryKind() {
        return AccessoryKind::insertFan();
    }





}