<?php

namespace app\modules\Fanavaran\controllers;

use app\modules\thirdParty\models\Inquiry;
use yii\web\Controller;
use yii\web\Response as webResponse;

class ThirdPartyController extends Controller
{



    public function behaviors(): array
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub




        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

        return $parent;
    }

    public function actionIndex() {
        $model = new Inquiry();
        $model->attributes = \Yii::$app->request->post();

        $res = $model->calculate();
        if ($res['status_code'] == 200)
        {
            return $res['content'];
        }

        return  $model->errors;
    }



    public function actionInquiry() {



    }

}