<?php

namespace app\modules\vehicle\models\changeData;

use app\modules\vehicle\models\VehicleUseType;

class VehicleUseTypeCD extends VehicleUseType
{

    public function fields()
    {
        $parent = parent::fields(); // TODO: Change the autogenerated stub

//        $parent = [];
        $parent['value'] = function () {
            return $this->id;
        };

        $parent['name'] = function () {
            return $this->name_fa;
        };

//        $parent['group_id'] = function () {
//          return $this->vehicle_group_id;
//        };





        return $parent;

    }
}