<?php

namespace app\modules\vehicle\models\changeData;

use app\modules\vehicle\models\VehicleSystem;

class VehicleSystemCD extends VehicleSystem
{

    public function fields()
    {
        $parent = parent::fields(); // TODO: Change the autogenerated stub


//        $parent = [];

        $parent['value'] = function () {
          return $this->id;
        };

        $parent['name'] = function () {
            return $this->name_fa;
        };


        return $parent;

    }

}