<?php

namespace  app\modules\vehicle\models\changeData;
use app\modules\vehicle\models\VehicleGroup;

class VehicleGroupCD extends VehicleGroup
{


    public $value;
    private $name;

    public function fields()
    {
        $parent =  parent::fields(); // TODO: Change the autogenerated stub

//        $parent = [];
        $parent['value'] = function () {
            return $this->id;
        };

        $parent['name'] = function () {
            return $this->name_fa;
        };


        return $parent;

    }


}