<?php

namespace app\modules\vehicle\models\changeData;

use app\modules\vehicle\models\VehicleKind;

class VehicleKindCD extends  VehicleKind
{


    public function fields()
    {
        $data= parent::fields(); // TODO: Change the autogenerated stub

//        $data = [];

        $data['value'] = function () {
            return $this->id;
        };
        
        $data['name'] = function () {
            return $this->name_fa;
        };

        return $data;
    }

}