<?php

namespace app\modules\vehicle\models\changeData;

use app\modules\vehicle\models\VehicleFuelType;

class VehicleFuelCD extends  VehicleFuelType
{

    public function fields()
    {
        $parent = parent::fields(); // TODO: Change the autogenerated stub


        $parent['value'] = function () {
            return $this->id;
        };



        return $parent;

    }

}