<?php

namespace app\modules\vehicle\controllers;

use app\modules\vehicle\models\PlaqueDesign;
use app\modules\vehicle\models\PlaqueKind;
use yii\rest\ActiveController;
use yii\web\Response as webResponse;

class PlaqueDesignController extends ActiveController
{

    public $modelClass = PlaqueDesign::class;

    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

        return $parent;
    }

}