<?php

namespace app\controllers;

use app\models\Auth;
use app\models\User;
use app\modules\Fanavaran\models\core\Curl;
use app\modules\order\models\Order;
use app\modules\order\models\OrderInfoInquiry;
use app\modules\thirdParty\models\UploadAttachFIleThirdPartDetail;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Yii;
use yii\filters\AccessControl;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;
use yii\filters\VerbFilter;

use yii\web\Response as webResponse;
use yii\web\UploadedFile;

class SiteController extends Controller
{


    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

//        $parent['authenticator'] = [
//            'class' => CompositeAuth::class,
//            'authMethods' => [
//                HttpBearerAuth::class,
//            ],
//            'except' => ['login']
//        ];

        return $parent;
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionLogin($call_number)
    {

        $call_number = trim($call_number);
        $access_phone = ['09372096736'];

        if (!in_array($call_number , $access_phone)) {
            throw new HttpException(403, 'access denied , call number: ' . $call_number);
        }

        $trans = Yii::$app->db->beginTransaction();
        try {
            $user = User::findOne(['call_number' => $call_number]);

            if (empty($user)) {
                $user = new User();
                $user->call_number = $call_number;
                $user->access_id = 1;
                $user->rule_id = 1;
                $user->status = 1;


                if (!$user->save()){
                    throw new BadRequestHttpException('fail login Errors: user_model');
                }
            }

            $auth = Auth::findOne(['user_id' => $user->id_user]);
            if (empty($auth))
            {
                $auth = new Auth();
                $auth->user_id = $user->id_user;
                $auth->ip = Yii::$app->request->userIP;
                $auth->agent = Yii::$app->request->userAgent;
                $auth->auth_kay = Yii::$app->security->generateRandomString(32);
            }

             $auth->expire_date = time() + (60 * 60) * 24;

            if (!$auth->save()) {
                 throw new BadRequestHttpException('fail login Errors: auth_model');
             }


            $trans->commit();
            return ['auth' => $auth ,'user' => $user];
        } catch (\Exception $err)
        {
            $trans->rollBack();
            \Yii::$app->response->statusCode = $err->getCode();
            return $err->getMessage();
        }


    }


    public function actionCallBack() {

        try {

            $secret= '6E01600AD06207B7F0ED8970E554656E19E401F936230A5E81C5F76079B2A33A9FE2114C940E266B9BB505309B2DF2132C403AE715A1A3E86F2CF3D5926F185E0578061CDDAE7ADA049ECD090B98C803A005894BC7AAA9723D783BDC323B2CF6582EE06A32B0CD2A9D37985124A629D0931DFB87BE15026295A98BFA161785D1'; # TODO: set secret kay

            $url = 'https://core.paystar.ir/api/pardakht/verify';


            $req = Yii::$app->request->post();

            if(isset($req['card_number'])) {
                $card_number = $req['card_number'];
            }

            if(isset($req['tracking_code'])) {
                $track_code = $req['tracking_code'];
            }


            $sign =  hash_hmac('SHA512', "10000".'#'."x5x2dn".'#'.$card_number."#".$track_code, $secret);

            $request_payment = [
                'amount' => '10000' ,
                'ref_num' => 'x5x2dn',
                'sign' => $sign,
            ];

            $response = Curl::httpRequest($url , [
                'Content-Type: ' .  'application/json',
                'Authorization: ' . "Bearer xo46glzv5y6d3"
            ], Curl::POST , json_encode($request_payment));

            return [
                'call_number' => $card_number,
                'track_code' => $track_code,
                'response' => $response,
                'req' => $req
            ];



        }catch (\Exception $err) {
            return $err;
        }


    }

    public function actionTest() {
        try {

//            $sign_key = '6E01600AD06207B7F0ED8970E554656E19E401F936230A5E81C5F76079B2A33A9FE2114C940E266B9BB505309B2DF2132C403AE715A1A3E86F2CF3D5926F185E0578061CDDAE7ADA049ECD090B98C803A005894BC7AAA9723D783BDC323B2CF6582EE06A32B0CD2A9D37985124A629D0931DFB87BE15026295A98BFA161785D1'; // کلید رمز نگاری درگاه که در پنل موجود هست

//            $request_parameters = [
//                'amount' => 10000,
//                'order_id' => '123456',
//                'callback' => 'https://example.com/callback',
//                'sign' => $signed_data
//            ];
//            $terminal_token = 'xo46glzv5y6d3'; // شناسه درگاه که در پنل موجود هست;

//            var_dump($response);die();
//
//            curl_close($ch);
//
//    if (is_null(json_decode($response))) {
//        var_dump($response);die();
//    }
//
//    $response = json_decode($response);
//
//    if ($response->status != 1) {
//        var_dump($response);die();
//    }
//
//    $token = $response->data->token;
//    var_dump($token);die();
//
//            $req = Yii::$app->request->post();
            /*
             * Request client:
             *
             * {
                "id": 4,
                "user_id": 1,
                "order_id": 4,
                "insurance_line_id": 5,
                "insurance_line_category_id": 4,
                "inquiry_id": 12,
                "detail_id": 5,
                "status": 2,
                "created_at": 1685547546,
                "updated_at": 1685547568,
                "updated_by": null,
                "created_by": null,
                "delete_mode": null
                }
             */


//



            #TODO: check Order Info , payment success

            #TODO: check



            $final_price = "10000";
            if (!is_numeric($final_price) || $final_price <= 0) {
                throw new HttpException(500 , 'check final price order !');
            }

            # set payment detail

            $secret= '6E01600AD06207B7F0ED8970E554656E19E401F936230A5E81C5F76079B2A33A9FE2114C940E266B9BB505309B2DF2132C403AE715A1A3E86F2CF3D5926F185E0578061CDDAE7ADA049ECD090B98C803A005894BC7AAA9723D783BDC323B2CF6582EE06A32B0CD2A9D37985124A629D0931DFB87BE15026295A98BFA161785D1'; # TODO: set secret kay


//            $signed_data = hash_hmac(
//                'sha512',
//                '10000#123456#https://example.com/callback',
//                $secret
//            );
            #TODO: متد HMAC و الگوریتم رمزنگاری SHA512 ,  amount#order_id#callback
            $sign =  hash_hmac('SHA512', $final_price.'#'."24323432".'#'.'https://ins-api.yarhis.ir/site/call-back', $secret);
//
            $request_payment = [
                'amount' => $final_price ,
                'order_id' => '24323432',
                'callback' => 'https://ins-api.yarhis.ir/site/call-back', # TODO: set call back url , (response)
                'sign' => $sign,
            ];


            $response = Curl::httpRequest('https://core.paystar.ir/api/pardakht/create' , [
                'Content-Type: ' .  'application/json',
                'Authorization: ' . "Bearer xo46glzv5y6d3"
            ], Curl::POST , json_encode($request_payment));

//            $ch = curl_init();
//            $options = array(
//                CURLOPT_RETURNTRANSFER  => true,
//                CURLOPT_ENCODING        => "",     // handle compressed
//                CURLOPT_AUTOREFERER     => true,   // set referrer on redirect
//                CURLOPT_CONNECTTIMEOUT  => 120,    // time-out on connect
//                CURLOPT_TIMEOUT         => 120,    // time-out on response
//                CURLOPT_POST            => 1,
//                CURLOPT_POSTFIELDS      => json_encode($request_payment),
//                CURLOPT_HTTPHEADER      => ['Authorization: Bearer ' . 'xo46glzv5y6d3','Content-Type:application/json'],
//                CURLOPT_SSL_VERIFYPEER  => false,
//                CURLOPT_URL             => 'https://core.paystar.ir/api/pardakht/create'
//            );
//            curl_setopt_array($ch, $options);
//            $response = curl_exec($ch);
//
////
////

            return  $response;


            # TODO: CALL URL , give token
            # https://core.paystar.ir/api/pardakht/create


            # TODO: inset row table for log DB (Trans action) => category , user , order , detail payment


            # redirect payment



        }catch (\Exception $err) {
            Yii::$app->response->statusCode = 500;
            return [
                'status' => false,
                'message' => $err->getMessage(),
                'file' => $err->getFile(),
                'code' => $err->getCode(),
                'line' => $err->getLine(),
            ];
        }





    }



    public function actionIndex() {
        return Yii::$app->user->identity;
    }


}
