<?php

namespace app\modules\order\controllers;

use app\modules\order\models\Order;
use app\modules\order\models\OrderInfoInquiry;
use app\modules\order\models\search\OrderInfoSearchModel;
use app\modules\order\models\search\OrderSearchModel;
use yii\data\ActiveDataProvider;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\rest\ActiveController;
use yii\web\NotFoundHttpException;
use yii\web\Response as webResponse;

class InfoController extends ActiveController
{

    public $modelClass = OrderInfoInquiry::class;

    public function behaviors(): array
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

        $parent['authenticator'] = [
            'class' => CompositeAuth::class,
            'authMethods' => [
                HttpBearerAuth::class,
            ],
            'except' => []
        ];


        return $parent;
    }

    public function actions(): array
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
//        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];
//        $actions['view']['findModel'] = [$this, 'oneDataProvider'];
        return $actions;
    }



}

