<?php

namespace app\modules\common\models\changeData;

use app\modules\common\models\AccessoryKind;

class AccessoryKindCD extends AccessoryKind
{


    public function fields()
    {
        $parent = parent::fields(); // TODO: Change the autogenerated stub


        $parent['value'] = function () {
            return $this->id;
        };

        $parent['name'] = function () {
            return $this->name_fa;
        };


        return $parent;

    }

    public static function find()
    {
        return parent::find()->where(['active' => 1]); // TODO: Change the autogenerated stub
    }



}