<?php

namespace app\modules\common\models\changeData;

use app\modules\common\models\CalcKind;

class CalcKindCD extends CalcKind
{


    public function fields()
    {
        $parent = parent::fields(); // TODO: Change the autogenerated stub


        $parent['value'] = function () {
            return $this->id;
        };


        return $parent;

    }


    public static function find()
    {
        return parent::find()->where(['active' => 1]); // TODO: Change the autogenerated stub
    }

}