<?php

namespace app\modules\common\controllers;

use app\modules\common\models\AdditionalCov;
use yii\rest\ActiveController;
use yii\web\Response as webResponse;

class AdditionalCovController extends ActiveController
{


    public $modelClass = AdditionalCov::class;

    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

        return $parent;
    }

    public function actions()
    {
        $parent = parent::actions(); // TODO: Change the autogenerated stub

        $parent['index']['pagination'] = false;

        return $parent;
    }
}