<?php

namespace app\modules\common\controllers;

use app\modules\common\models\changeData\InsuranceCorpCD;
use app\modules\common\models\InsuranceCorp;
use yii\web\Controller;
use yii\web\Response as webResponse;

/**
 * Default controller for the `common` module
 */
class DefaultController extends Controller
{
    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

        return $parent;
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }


    public function actionCustomerInsuranceCorp(): array
    {
        $modelData = InsuranceCorpCD::find()->where(['active' => 1])->all();
        $mac = [['value' => 1 , 'name' => ' صفر کیلومتر' ]];

        $data = array_merge($mac , $modelData );

        return $data;
    }
}
