<?php

namespace app\modules\common\controllers;

use app\modules\common\models\DriverType;
use yii\rest\ActiveController;
use yii\web\Response as webResponse;

class DriverTypeController extends ActiveController
{


    public $modelClass = DriverType::class;

    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $parent['corsFilter'] = [
            'class' => \yii\filters\Cors::class,
        ];

        $parent['contentNegotiator'] = [
            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [ 'application/json' => webResponse::FORMAT_JSON ]
        ];

        return $parent;
    }
}