<?php

namespace app\modules\bodyPart\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "body_part_inquiry_additional_cov".
 *
 * @property int $id
 * @property int $body_part_inquiry_id
 * @property int|null $cov_kind_id
 * @property int|null $cov_rate_id
 * @property float|null $daily_commitment_amount
 * @property float|null $dmg_effective_percent
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $delete_mode
 */
class BodyPartInquiryAdditionalCov extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'body_part_inquiry_additional_cov';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['body_part_inquiry_id'], 'required'],
            [['body_part_inquiry_id', 'cov_kind_id', 'cov_rate_id', 'created_at', 'updated_at', 'delete_mode'], 'integer'],
            [['daily_commitment_amount', 'dmg_effective_percent'], 'number'],
        ];
    }

    public function behaviors()
    {
        return [TimestampBehavior::class]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'body_part_inquiry_id' => 'Body Part Inquiry ID',
            'cov_kind_id' => 'Cov Kind ID',
            'cov_rate_id' => 'Cov Rate ID',
            'daily_commitment_amount' => 'Daily Commitment Amount',
            'dmg_effective_percent' => 'Dmg Effective Percent',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'delete_mode' => 'Delete Mode',
        ];
    }
}
